### ISSUE TITLE
Check TinyOS timer accuracy

### ISSUE THREAD

**Issue by gitbaum** [ibr-alg/wiselib#13]
Hint by Martin Bor:
"""
One small remark that I forgot to mention: you know that the timers in
TinyOS are 'binary'? One second of real time are 1024 ticks on a TinyOS
TMilli Timer. If you expect that 1000 ticks equals one second, your
timing would be off by 23 ms. See also
http://www.tinyos.net/tinyos-2.x/doc/html/tep102.html#precision-width-and-accuracy
"""

**Comment by Droggelbecher** [comment]
Handled in issue #38
