### ISSUE TITLE
String size() vs. length()

### ISSUE THREAD

**Issue by slohse** [ibr-alg/wiselib#14]
Hi,

I could be wrong here, but shouldn't string_dynamic and static_string offer the methods they have in common with a common signature? So then you could pass them as template parameters, depending on which you want to use.
In particular, at the moment string_dynamic has a size() method, where static_string has a length() method. Shouldn't those be called by the same name in both implementations?

**Comment by gitbaum** [comment]
Hi,

thanks for the hint! Yes, it seems that there is sth wrong. We will have a look at it.

Best,
Tobias

**Comment by shubhamsomani** [comment]
Cant we just add a size() function in static_string which would return length, so that we would have size and length functions in both string_dynamic & static_string removing ambiguity?

**Comment by Droggelbecher** [comment]
This is -- thanks to your pull request -- done now right?

**Comment by shubhamsomani** [comment]
yup
