### ISSUE TITLE
Add sec/millis to clock concept

### ISSUE THREAD

**Issue by gitbaum** [ibr-alg/wiselib#17]
Some time ago, we decided to add 
  uint16_t microseconds( time_t time );
  uint16_t milliseconds( time_t time );
  uint32_t seconds( time_t time );
to the clock, because time_t can be double, int , a struct, ...., and thus to provide generic access.

Somehow the methods are not in the concept yet...

**Comment by ghost** [comment]
https://github.com/ibr-alg/wiselib/pull/18
