### ISSUE TITLE
Arduino debug producing incorrect output when given multiple arguments

### ISSUE THREAD

**Issue by mnikander** [ibr-alg/wiselib#39]
The following code fragment out of a test function:

debug_->debug("start_address = %d", start_address);
debug_->debug("wr_success = %d", wr_success);
**debug_->debug("test_write_read_1024(%d) = %d", start_address, wr_success);**
debug_->debug("wr_success = %d", wr_success);

Where start_address is a size_t and wr_success is a bool, results in the following output on the PC:

start_address = 0
wr_success = 1
**test_write_read_1024(0) = 1**
wr_success = 1

On Arduino however the following output is generated:

start_address = 0
wr_success = 1
**test_write_read_1024(0) = 0**
wr_success = 1

As can be seen, the actual values of the variables are the same, but the debug function produces incorrect output. I've had multiple other similar cases where the Arduino-debug function has consistently produced incorrect output. If the problem does occur, then splitting the debug statement into multiple separate statements produces correct output. Could it be that the arduino-debug function's number of arguments is limited in some way? If it is, it's not systematic though, the following code:

bool foo = 1;
int bar = 50;
bool blah = 1;
debug_->debug("foo = %d, bar = %d, blah = %d", foo, bar, blah);

Produces the correct output:

foo = 1, bar = 50, blah = 1

**Comment by Droggelbecher** [comment]
When you call a function with a variable parameter list such as debug (or printf for that matter),
arguments are pushed on the stack in order you provide them. The only way for the function to figure out
how to interpret the resulting block of binary data on the stack as individual arguments in this case is the format string you are providing.

This is especially crucial, when the arguments have different length: Whereas on PC lots of data types are aligned internally to be effectively 32 bits long, on other architectures that might not be the case,
and thus the reading of the argument might "slip" if you just write "%d" in the format string, promising the arguments will be of length sizeof(int).

That is, if sizeof(size_t) is bigger than sizeof(int), on arduino, that might be the reason for your problem.

Could you do the following:
Find out what sizeof(size_t) and sizeof(bool) are in your test code on your arduino and post it here,
and also try to run your function modified to this:

debug_->debug("test_write_read_1024(%d) = %d", (int)start_address, (int)wr_success);

and see if that solves the problem?

**Comment by mnikander** [comment]
debug_->debug("sizeof(size_t) = %d", sizeof(size_t));
debug_->debug("sizeof(bool) = %d", sizeof(bool));
debug_->debug("sizeof(int) = %d", sizeof(int));
debug_->debug("test_write_read_1024(%d) = %d", start_address, wr_success);
**debug_->debug("test_write_read_1024(%d) = %d", (int)start_address, (int)wr_success);**

Output:

sizeof(size_t) = 4
sizeof(bool) = 1
sizeof(int) = 2
test_write_read_1024(0) = 0
**test_write_read_1024(0) = 1**

Adding the explicit casts seems to solve the issue. If as you say the problem is that the readings of the argument "slips" though, then how come the following code fragment works fine?

bool foo = 1;
int bar = 50;
bool blah = 1;
debug_->debug("foo = %d, bar = %d, blah = %d", foo, bar, blah);

**Comment by mnikander** [comment]
It seems that int (2 bytes) and bool (1 byte) don't cause any trouble, perhaps bool's are padded up to a size of 2 bytes or something. Things seem to break down only once you throw the size_t (4 bytes) into the mix.

**int** foo = 42;
bool bar = 0;
int blah = 42;
debug_->debug("mark_0: foo = %d, bar = %d, blah = %d", foo, bar, blah);

**size_t** foo1 = 42;
bool bar1 = 0;
int blah1 = 42;
debug_->debug("mark_1: foo = %d, bar = %d, blah = %d", foo1, bar1, blah1);

Output:

mark_0: foo = 42, bar = 0, blah = 42
mark_1: foo = 42, bar = 0, blah = 0

**Comment by Droggelbecher** [comment]
I didn't look it up but my guess is, that similar to x86 aligning to 4-byte-positions, arduino might align to 2-byte positions.

That is: the compiler takes care that every variable/parameter that is 2 bytes long or longer starts at an even position.
say the stack area for parameters when calling debug() starts at X (with X being even), then foo will be placed at X directly, bar is 2 byte long and must be aligned, so it can not be placed at X+1 but the memory after foo will be padded by one byte so bar starts at X+2.
Then blah gets placed at X+4.

This way all 3 fields happen to be two byte (=sizeof(int)) long, and everything works (which is pure luck, if you change bar to a bool it will probably break again, might even crash as your stack contains 3 bytes where 6 are expected).

This alignment stuff can really cost you some nights. So whenever you got the feeling something near a debug statement seems fishy, always double check your parameter sizes first ;)
