### ISSUE TITLE
 Makefile error in wiselib library

### ISSUE THREAD

**Issue by TiNkU-dArsHan** [ibr-alg/wiselib#43]
Makefile in the folder "geniric_apps/convergecast/" uses

$(WISELIB_PATH)
$(WISELIB_GENERIC_APPS)

variable to include Makefile.local and Makefile which are in the parent dir
and whose initialization are not visible

got error which compiling for Shawn

---

$ make shawn
Makefile:19: /../apps/generic_apps/Makefile.local: No such file or directory
Makefile:20: /Makefile: No such file or directory
make: **\* No rule to make target `/Makefile'.  Stop.
$

---

**Comment by Droggelbecher** [comment]
this should have be fixed in https://github.com/ibr-alg/wiselib/commit/2f02378634800de94fcb284db47b99ef93754cc5

can you confirm that?

**Comment by TiNkU-dArsHan** [comment]
Yes, its fixed
