### ISSUE TITLE
How to run Wiselib - RDF Provider?

### ISSUE THREAD

**Issue by Madhubhani** [ibr-alg/wiselib#65]
I want to use Wiselib to convert sensor data into RDF and then store them in the Wiselib store.

I followed the steps in Github Wiki page to compile and run it in Ubuntu. I compiled an existing example application, wiselib/apps/generic_apps/rdfprovider_test/ and an executable file got created. But the problem is that I face an error (Segmentation fault) when I run that executable file.
__________________________________________________________
$ ./rdfprovider_test
--- init codec_ts
--- init broker
--- inserting documents
create doc1
init free: -1
create doc1
init free: -1
create doc1
init free: -1
ins
init free: -1
ins
init free: -1
ins
init free: -1
ins
ins
ins
ins
ins
ins
ins
ins
ins done
--- testing broker
masks=1 2 4

--- iter doc1:
Segmentation fault (core dumped)
__________________________________________________________
Could you please help me to fix this problem? If I have done something wrong, could you please give me some instructions to run it?

Thank you

**Comment by moodgorning** [comment]
Hi Madhubhani, I was involved in the wiselib 7 years ago and just accidentally stumbled over your comment. I fear all original contributors to the wiselib have moved on and the project hasn't been worked on or maintained in years now. As such it is very unlikely anyone will be able to help you

**Comment by Madhubhani** [comment]
Hi Max,
Okay, I understand. Thank you so much!
